theme: jekyll-theme-slate
title: Machine Learning for Creativity and Design
description: A one-day workshop at [NIPS 2017](https://nips.cc/), Long Beach, CA, USA.<br/>Friday Dec 8th 8:00 AM - 06:30 PM
