theme: jekyll-theme-slate
title: Machine Learning for Creativity and Design
description: <a href="https://nips.cc/">NIPS 2017</a> Workshop, Long Beach, CA, USA.
eventdate: Friday Dec 8th 8:00 AM - 06:30 PM
