theme: jekyll-theme-slate
title: Machine Learning for Creativity and Design
description: A one-day workshop at <a href="https://nips.cc/">NIPS 2017</a>, Long Beach, CA, USA.
eventdate: Friday Dec 8th 8:00 AM - 06:30 PM
